import { defineConfig } from 'vitest/config';
import { fileURLToPath } from 'node:url';

export default defineConfig({
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('.', import.meta.url)),
    },
  },
  test: {
    environment: 'node',
    include: ['tests/{unit,integration}/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary'],
      include: [
        'app/api/account/deletion/handler.ts',
        'app/api/account/terms-consent/handler.ts',
        'components/billing-checkout-boundary.tsx',
        'components/account-deletion-boundary.tsx',
        'components/history-view.tsx',
        'components/privacy-request-boundary.tsx',
        'components/terms-consent-boundary.tsx',
        'components/session-notes-app.tsx',
        'components/use-history-window.ts',
        'lib/application/account-deletion-handoff.ts',
        'lib/application/account-deletion-runner.ts',
        'lib/application/billing-ui.ts',
        'lib/application/card-body-text-lookup.ts',
        'lib/application/card-editor-index.ts',
        'lib/application/full-network-layout-controller.ts',
        'lib/application/history-window.ts',
        'lib/application/legal-commerce.ts',
        'lib/application/launch-compliance.ts',
        'lib/application/legal-terms.ts',
        'lib/application/privacy-disclosure.ts',
        'lib/application/privacy-processing-registry.ts',
        'lib/application/privacy-request-ui.ts',
        'lib/application/logout-coordination.ts',
        'lib/application/notes-access.ts',
        'lib/application/notes-database-scope.ts',
        'lib/application/logout-purge-progress.ts',
        'lib/application/logout-purge-runner.ts',
        'lib/application/logout-purge.ts',
        'lib/application/logout-runtime-coordination.ts',
        'lib/application/notes-operation-lifecycle.ts',
        'lib/application/notes-runtime.ts',
        'lib/application/sync-v2-client.ts',
        'lib/application/terms-consent-ui.ts',
        'lib/client/browser-clock.ts',
        'lib/client/browser-account-deletion-progress.ts',
        'lib/client/browser-account-deletion.ts',
        'lib/client/browser-control-database.ts',
        'lib/client/browser-logout-coordination.ts',
        'lib/client/browser-logout-purge-progress.ts',
        'lib/client/browser-logout-purge.ts',
        'lib/client/browser-service-worker-purge.ts',
        'lib/client/http-billing-ui.ts',
        'lib/client/http-privacy-request.ts',
        'lib/client/local-privacy-request.ts',
        'lib/client/card-editor-index-cache.ts',
        'lib/client/browser-connectivity.ts',
        'lib/client/http-account-deletion.ts',
        'lib/client/http-sync-transport.ts',
        'lib/client/id-generator.ts',
        'lib/client/legacy-notes-runtime.ts',
        'lib/client/terms-consent-ui.ts',
        'lib/client/vault-notes-runtime.ts',
        'lib/client/fake-logout-purge-progress.ts',
        'lib/client/connections-layout-worker.ts',
        'lib/client/full-network-layout-worker.ts',
        'lib/client/notes-store.tsx',
        'lib/client/offline.ts',
        'lib/domain/**/*.ts',
        'lib/editor/body-document.ts',
        'lib/graph/full-network-layout-protocol.ts',
        'lib/graph/full-network-layout.ts',
        'lib/graph/full-network-routing.ts',
        'lib/sync/**/*.ts',
        'lib/storage/**/*.ts',
        'server/**/*.ts',
      ],
    },
  },
});
